/* Generated By:JJTree&JavaCC: Do not edit this line. ProgramConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ProgramConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER = 4;
  /** RegularExpression Id. */
  int PUBLIC = 5;
  /** RegularExpression Id. */
  int STATIC = 6;
  /** RegularExpression Id. */
  int VOID = 7;
  /** RegularExpression Id. */
  int MAIN = 8;
  /** RegularExpression Id. */
  int CLASS = 9;
  /** RegularExpression Id. */
  int EXTENDS = 10;
  /** RegularExpression Id. */
  int INT = 11;
  /** RegularExpression Id. */
  int BOOLEAN = 12;
  /** RegularExpression Id. */
  int STRING = 13;
  /** RegularExpression Id. */
  int RETURN = 14;
  /** RegularExpression Id. */
  int IF = 15;
  /** RegularExpression Id. */
  int ELSE = 16;
  /** RegularExpression Id. */
  int WHILE = 17;
  /** RegularExpression Id. */
  int NEW = 18;
  /** RegularExpression Id. */
  int THIS = 19;
  /** RegularExpression Id. */
  int TRUE = 20;
  /** RegularExpression Id. */
  int FALSE = 21;
  /** RegularExpression Id. */
  int LENGTH = 22;
  /** RegularExpression Id. */
  int IDENTIFIER = 23;
  /** RegularExpression Id. */
  int LEFTKEY = 24;
  /** RegularExpression Id. */
  int RIGHTKEY = 25;
  /** RegularExpression Id. */
  int LSB = 26;
  /** RegularExpression Id. */
  int RSB = 27;
  /** RegularExpression Id. */
  int COMMA = 28;
  /** RegularExpression Id. */
  int SEMICOLON = 29;
  /** RegularExpression Id. */
  int LCB = 30;
  /** RegularExpression Id. */
  int RCB = 31;
  /** RegularExpression Id. */
  int EQUAL = 32;
  /** RegularExpression Id. */
  int AND = 33;
  /** RegularExpression Id. */
  int LT = 34;
  /** RegularExpression Id. */
  int SUM = 35;
  /** RegularExpression Id. */
  int SUB = 36;
  /** RegularExpression Id. */
  int MUL = 37;
  /** RegularExpression Id. */
  int DIV = 38;
  /** RegularExpression Id. */
  int EXC = 39;
  /** RegularExpression Id. */
  int POINT = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "<INTEGER>",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"class\"",
    "\"extends\"",
    "\"int\"",
    "\"boolean\"",
    "\"String\"",
    "\"return\"",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"new\"",
    "\"this\"",
    "\"true\"",
    "\"false\"",
    "\"length\"",
    "<IDENTIFIER>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"&&\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"!\"",
    "\".\"",
  };

}
