/* Generated By:JavaCC: Do not edit this line. ProgramTreeConstants.java Version 6.0_1 */
public interface ProgramTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCLASSDECLARATION = 1;
  public int JJTDECLARATION = 2;
  public int JJTVARDECLARATION = 3;
  public int JJTMAINDECLARATION = 4;
  public int JJTMETHODDECLARATION = 5;
  public int JJTTYPE = 6;
  public int JJTINT = 7;
  public int JJTSTATEMENT = 8;
  public int JJTEXPRESSION = 9;
  public int JJTEXPRESSIONL = 10;
  public int JJTPOINT = 11;
  public int JJTAFTERPOINT = 12;
  public int JJTNEW = 13;
  public int JJTAFTERNEW = 14;
  public int JJTEXPRESSIONTERMINALS = 15;


  public String[] jjtNodeName = {
    "Program",
    "ClassDeclaration",
    "Declaration",
    "VarDeclaration",
    "MainDeclaration",
    "MethodDeclaration",
    "Type",
    "Int",
    "Statement",
    "Expression",
    "ExpressionL",
    "Point",
    "AfterPoint",
    "New",
    "AfterNew",
    "ExpressionTerminals",
  };
}
/* JavaCC - OriginalChecksum=70070e405709e293d1811bccac2acb83 (do not edit this line) */
